{{- if .Values.devsecops.AuthorizationPolicy.rules -}}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "push-cache-backend.fullname" . }}
  labels:
    {{- include "push-cache-backend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "push-cache-backend.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  {{-  tpl (toYaml .Values.devsecops.AuthorizationPolicy.rules) . | nindent 4 }}
{{- end }}
