---
hams:
  address: 127.0.0.1:8079
  prefix: hams
  logging: true
  checks:
    timeout: 5
    fails: 2
    preflights: []
    # - http://localhost:4201
    shutdowns: []
runtime:
  stack_size: 3145728
  threads: 4
  name: push-cache
webservice:
  address: http://0.0.0.0:8080/cache
  forwarding_headers: []
kafka:
  brokers: kafka://localhost:9092
  group_id: pushcgroup
  topic: pcache-users
  schema_registry_url: http://localhost:8081
  cache_max_age: 300s
  fetch_metadata_timeout: 5s
  offset_reset: earliest
startup_checks:
  fails: 2
  timeout: 5s
  enabled: true
